services:
  kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports: ["9092:9092"]
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://kafka:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  flink-jobmanager:
    build: .
    container_name: flink-jobmanager
    ports: ["8081:8081"]
    command: jobmanager
    volumes:
      - ./jars:/opt/flink/lib/extra
      - ./scripts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        pipeline.classpaths: file:///opt/flink/lib/extra/flink-sql-connector-kafka-3.3.0-1.20.jar

  flink-taskmanager:
    build: .
    container_name: flink-taskmanager
    depends_on: [flink-jobmanager]
    command: taskmanager
    volumes:
      - ./jars:/opt/flink/lib/extra
      - ./scripts:/opt/flink/usrlib
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        pipeline.classpaths: file:///opt/flink/lib/extra/flink-sql-connector-kafka-3.3.0-1.20.jar